Js6aNZW0
47.75.124.29
r0eIbwBcOE
1.通过start-mongodb-auth.sh启动mongodb
2.数据库增加安全模式后，初始化一个“userAdminAnyDatabase”非常重要
通过客户端连接，使用admin数据库， 执行如下脚本：
db.createUser({'user':'boss', 'pwd':'boss', 'roles':[{'role':'userAdminAnyDatabase', 'db':'admin'}]})

3.使用刚创建成功的用户登录：db.auth("boss","boss");
4.切换到其他数据库（use xxx），创建读写权限用户：
db.createUser({'user':'lison','pwd':'lison','roles':[{'role':'readWrite','db':'lison'}]})
5.使用读写权限用户lison登录，db.auth("lison","lison")，登录后测试;


ps:也可以以非auth模式启动，然后创建用户后，用auth模式启动
