spring:
  ###文件上传限制
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
  ###redis配置
  redis:
    host: 47.75.124.29
    port: 46379
    password: 123456
    maxTotal: 60000
    maxIdle: 1000
    maxWaitMillis: 1000
    database: 2
  mongodb:
    host: 47.75.124.29
    port: 27017
    database: exchange
    username: dev
    password: 123456
#mybatis:
#  mapperLocations: classpath*:/com/exchang/**/mapper/*Mapper.xml

### 短信
hb:
  uname: 10690356
  passwd: Whztyz-29

### 文件上传
oss:
  # OSS访问编号
  accessKeyId: LTAIp4oYoDb2fhKV
  # OSS访问密钥
  accessKeySecret: ZGMCYSSq8FZ7xXMqpyhzaHvmSZ6PyN
  # OSS存储空间
  bucketName: shanghai-ex-file
  file:
    maxsize: 102400
    file_img_extension: bmp,jpg,gif,jpeg,png


# 交易所信息
exchange:
  # 交易所发行货币英文名称（只允许大写）
  coinNameEn: BRT
  # 谷歌认证参数为交易所的域名
  googleAuthPath: www.bitrr.io
  # 交易所英文名称（只允许大写）
  sysNameEn: BITRR
  # 交易所中文名称
  sysNameZh: 比特人人

email:
  # 用来发送验证码的邮箱账号
  account: xuys24@163.com
  # 用来发送验证码的邮箱密码
  pwd: b1lT7x
  # 定义发送邮件的途径（1 gmail邮件    2 QQ邮箱    3 163邮箱）
  type: 3

### 实名认证
authapi:
  host: "http://idenauthen.market.alicloudapi.com"
  path: "/idenAuthentication"
  appcode: "6ca4adeb760e4e81a0f2807a4cbca8a3"
  apiSuccess: "0000"
  apiFailure: "0008"
  apiCheckFailure: "0004"
  total: 5

### 挖矿密钥
mining:
  nbPwd: "af4fcef5-d617-4751-aa7d-630733df6136"
