-- 小组
CREATE TABLE `tb_group`(
  `group_id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '小组 编号',

  `group_name` VARCHAR(50) DEFAULT NULL COMMENT '小组名',

  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',

	PRIMARY KEY (`group_id`)
)
COLLATE='utf8_unicode_ci'
ENGINE=INNODB
ROW_FORMAT=DEFAULT
DEFAULT CHARSET=utf8
COMMENT='小组表'
AUTO_INCREMENT=1
;

-- 小组 与 用户 关联表
CREATE TABLE `tb_group_user`(

  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '关联ID',

  `group_id` BIGINT(11) NOT NULL COMMENT '小组 编号',

  `user_id` BIGINT(11) NOT NULL COMMENT '用户编号',

  `group_name` VARCHAR(20) DEFAULT NULL COMMENT '小组名',

  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',

	PRIMARY KEY (`id`)
)
COLLATE='utf8_unicode_ci'
ENGINE=INNODB
ROW_FORMAT=DEFAULT
DEFAULT CHARSET=utf8
COMMENT='小组 与 用户 关联表'
AUTO_INCREMENT=1
;

-- 用户表
CREATE TABLE `tb_user` (
  `user_id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '用户编号',

  `uname` VARCHAR(20) DEFAULT NULL COMMENT '姓名名',
  `icon_img_url` VARCHAR(128) DEFAULT NULL COMMENT '头像',
  `mobile` VARCHAR(20) DEFAULT NULL COMMENT '手机号',

	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',

	PRIMARY KEY (`user_id`),
	UNIQUE KEY `uniq_mobile` (`mobile`)
)
COLLATE='utf8_unicode_ci'
ENGINE=INNODB
ROW_FORMAT=DEFAULT
DEFAULT CHARSET=utf8
COMMENT='用户表'
AUTO_INCREMENT=98000000
;

-- 用户登录表
DROP TABLE IF EXISTS `tb_user_agent`;
CREATE TABLE `tb_user_agent` (
  `user_agent_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户登录编号',
  `user_id` BIGINT(20) NOT NULL COMMENT '用户编号',

  `login_name` varchar(50) DEFAULT NULL COMMENT '登录名',
	`telephone` varchar(20) DEFAULT NULL COMMENT '电话',

	`login_pwd` varchar(100) DEFAULT NULL COMMENT '登录密码',
	`last_login_time` TIMESTAMP NULL COMMENT '最后登录时间',
	`login_count` INTEGER NULL COMMENT '登录次数',

	`deleted` SMALLINT(1) DEFAULT '0' COMMENT '0 有效 1 无效',

	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',

	PRIMARY KEY (`user_agent_id`),
	UNIQUE KEY `uniq_telephone` (`telephone`)
)
COLLATE='utf8_unicode_ci'
ENGINE=INNODB
ROW_FORMAT=DEFAULT
DEFAULT CHARSET=utf8
COMMENT='用户登录表'
AUTO_INCREMENT=1
;
